CC=gcc
CFLAGS=-g -pthread

all: ejemplo1 ejemplo2 ejemplo3 ejemplo4

ejemplo1: ejemplo1.c
	$(CC) $(CFLAGS) -o ejemplo1 ejemplo1.c

ejemplo2: ejemplo2.c
	$(CC) $(CFLAGS) -o ejemplo2 ejemplo2.c

ejemplo3: ejemplo3.c
	$(CC) $(CFLAGS) -o ejemplo3 ejemplo3.c

ejemplo4: ejemplo4.c
	$(CC) $(CFLAGS) -o ejemplo4 ejemplo4.c

clean:
	rm -f ejemplo1 ejemplo2 ejemplo3 ejemplo4
